### ISSUE TITLE
zig-run should save the current buffer

### ISSUE THREAD

**Issue by indradhanush** [ziglang/zig-mode#106]
First of all thank you so much for this package! ❤️

I just wrote my own function to save the current buffer when I execute `zig-run` with `C-x C-r` in doomemacs:

```elisp
(use-package! zig-mode
  :config
  (defun my/save-buffer-and-execute-zig-run ()
    "Save the current buffer and execute `zig-run`."
    (interactive)
    (save-buffer)
    (zig-run))

  (define-key zig-mode-map (kbd "C-c C-r") #'my/save-buffer-and-execute-zig-run))
```

Without this most of the time I found myself pressing `C-c C-r` only to realise that I haven't saved the file yet. 

Should `zig-run` **always** save the buffer when it is executed? I'd be happy to send in a PR but wanted to check first before I sent one.

**Comment by ve-nt** [comment]
I agree that Emacs should prompt to save all buffers before running any zig commands. This is pretty standard behavior in emacs as `M-x compile` will remind you to save your buffers before running anything. I have submitted a pull request that adds this feature.
