### ISSUE TITLE
Zig-mode mistaking function calls as variables

### ISSUE THREAD

**Issue by Dappstr** [ziglang/zig-mode#107]
After installing the latest version of Zig-mode for Emacs 29.4, it appears many things are being mistaken for variables, such as methods and non-method function calls. Not sure if this is expected.
![Screenshot 2024-09-16 000555](https://github.com/user-attachments/assets/991628ff-2755-41b0-b261-ff5257ea395d)
![Screenshot 2024-09-16 001203](https://github.com/user-attachments/assets/44156ad2-5dec-4769-a819-89d3397e8c59)

**Comment by jcs090218** [comment]
Are you using `tree-sitter-langs`? 🤔

**Comment by Dappstr** [comment]
> Are you using `tree-sitter-langs`? 🤔
@jcs090218 Yes I am. I'm on Windows and it was the easiest way to get tree-sitter up and working as I'm on Windows. I've tried downloading grammars and wasn't able to find the DLL's despite "tree-sitter generate" running without error and tree-sitter test
passing (at least for C grammars)

**Comment by jcs090218** [comment]
Could a recent commit of tree-sitter-langs cause it? See https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/688.
