### ISSUE TITLE
Replace this with a cc-mode derived mode

### ISSUE THREAD

**Issue by liampwll** [ziglang/zig-mode#13]
Replacing this mode with a cc-mode derived mode would provide better integration with other emacs packages for c-like languages and allow users cc-mode configuration to work in zig-mode.

**Comment by svmhdvn** [comment]
I would be interested in taking a look at this!

**Comment by ilohmar** [comment]
Just my opiniion as a long-time Emacser: Please do not go this way!  Emacs' cc-mode is barely maintainable as is, and even core Emacs is experimenting with alternatives.  The future will definitely not be in depending on cc-mode...

**Comment by jcs090218** [comment]
Yeah, I agree. `cc-mode` has a few serious bugs that are difficult to deal with. 

I am closing this issue for now, but feel free to post any other suggestions!
