### ISSUE TITLE
Using new `rx` features means the minimal requirement is emacs 27

### ISSUE THREAD

**Issue by larme** [ziglang/zig-mode#43]
The new zig-mode failed to compile on older version like 26.3. The reason is that emacs 27's rx's `regexp` and new `literal` accept arbitrary lisp as arguments while older ones only accept string known at compile time.

So we need to either bump the minimal requirement to 27 or fix it (e.g. by wrapping the entire file inside a macro)

**Comment by joachimschmidt557** [comment]
This is a duplicate of #42.

**Comment by larme** [comment]
sorry missed that one. I will close this issue.
