### ISSUE TITLE
string highlighting doesn't stop if end quote is preceded by an escaped backslash

### ISSUE THREAD

**Issue by travv0** [ziglang/zig-mode#47]
An example from std.os.windows, everything after the following line is highlighted as a string because it sees the end quote as escaped:
```js
const prefix_u8 = "\\DosDevices\\";
```

**Comment by endragor** [comment]
Possibly related: if a multi-line string literal ends with an empty line, everything after that line is highlighted as a string. Example:
```zig
const test_str =
    \\I need the empty line
    \\
;
```

**Comment by endragor** [comment]
Ah, you already fixed that. So nevermind :)

**Comment by travv0** [comment]
Yeah, I got that fixed but my emacs knowledge wasn't enough for me to figure this one out.  It seems like the function currently used for highlighting multiline strings might be overkill since you'd think a simple regex would do the trick, but it seems like there's some sort of "priority" to what gets highlighted so when I tried to highlight based on a regex match, it only matched strings that didn't have highlighted keywords in them.
