### ISSUE TITLE
Prefer flycheck and lsp-ui to *zig-fmt* split window

### ISSUE THREAD

**Issue by toyboot4e** [ziglang/zig-mode#50]
Someone on Discord gave me this code that allows `flycheck` to work with `zig-mode`:

```elisp
(flycheck-define-checker zig
    "A zig syntax checker using the zig-fmt interpreter."
    :command ("zig" "fmt" (eval (buffer-file-name)))
    :error-patterns
    ((error line-start (file-name) ":" line ":" column ": error: " (message) line-end))
    :modes zig-mode)
(add-to-list 'flycheck-checkers 'zig)
```

And both `flycheck` and `lsp-ui` worked:

<img width="956" alt="flycheck" src="https://user-images.githubusercontent.com/47905926/101539047-3edc9380-39e1-11eb-8d0e-908b88f2e611.png">

However, `zig-mode` always opens `*zig-fmt*` split window. This is duplicate, so it's nice if we can suppress the behavior.

Thank you.

**Comment by q60** [comment]
i'm stumbling upon this annoying split window issue too. so it's still here. will someone hear us and do something with it? @AndreaOrru ? or someone...

![image](https://user-images.githubusercontent.com/61933599/131390837-3cff7e5b-df22-4208-8700-bbba9dc51cc3.png)

**Comment by joachimschmidt557** [comment]
@toyboot4e @q60 Does #62 address this issue? If yes, I'll merge that right away.

**Comment by q60** [comment]
> @toyboot4e @q60 Does #62 address this issue? If yes, I'll merge that right away.

yea, that's a fix for this problem

**Comment by joachimschmidt557** [comment]
#62 introduces a new `defcustom` which disables showing the `*zig-fmt*` buffer when formatting exits with errors.

**Comment by toyboot4e** [comment]
Yeah it's working. Super comfortable, thanks!
