### ISSUE TITLE
Highlighting gets messed up if skipping to the end of a long file with strings

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig-mode#52]
When viewing src/main.zig (of zig) and skipping to the end of the file, it displays everything as strings. 
![image](https://user-images.githubusercontent.com/58830309/108613059-311d9400-73bc-11eb-8c65-07472e16f1de.png)
I have also experienced this with the vim plugin, but it would be nice if this didn't happen.

**Comment by joachimschmidt557** [comment]
I think this is still an issue related to https://github.com/ziglang/zig-mode/issues/22

**Comment by g-w1** [comment]
Ah, should that be re-opened?

**Comment by joachimschmidt557** [comment]
I agree. I think that issue should be reopened as the handling of multiline strings was improved by #46 but not fixed completely as we can see.
