### ISSUE TITLE
zig-test-buffer: don't use release-fast?

### ISSUE THREAD

**Issue by bnjmnt4n** [ziglang/zig-mode#56]
Is there any rationale for using `release-fast` for `zig-test-buffer`? Personally, I would think that testing should use the debug release mode by default to catch any illegal behaviour, since that's what testing should flag out.

**Comment by joachimschmidt557** [comment]
With https://github.com/ziglang/zig-mode/pull/55 it will be possible to customize the optimization mode for tests.

**Comment by bnjmnt4n** [comment]
:+1: will close this when that PR lands in that case.
