### ISSUE TITLE
Format on save makes the cursor jump randomly

### ISSUE THREAD

**Issue by nitinprakash96** [ziglang/zig-mode#73]
Here's a screencast to show what I mean by "make the cursor jump"

https://user-images.githubusercontent.com/15181803/187585877-3fbb3b23-c6dc-48e6-9f00-1820c935254c.mov

**Comment by joachimschmidt557** [comment]
Does this issue also occur when using the [reformatter branch](https://github.com/ziglang/zig-mode/pull/51)? In status quo, `revert-buffer` is responsible for restoring the cursor location. reformatter uses a custom cursor location recovery algorithm, which in my experience is pretty accurate.

**Comment by nitinprakash96** [comment]
Closing as this does not happen anymore on master branch. Sorry it took me a while because I switched to vscode because these jumps got annoying. But I'm happy with emacs again.
