### ISSUE TITLE
README makes no mention of reformatter dependency

### ISSUE THREAD

**Issue by lifelike** [ziglang/zig-mode#80]
Got an ugly error message when trying to load zig-mode:

`File mode specification error: (file-error Cannot open load file Not a directory reformatter)`

Turns out there is a dependency on emacs-reformatter. Only figured it out because I tried to run the tests and I noticed the script installed reformatter using elpa.

It would be helpful if the README could mention adding emacs-reformatter's reformatter.el to load-path before trying to load zig-mode.

**Comment by joachimschmidt557** [comment]
Good point, I forgot to add a notice to the README about `reformatter`. I'll open up a PR for this soon.
