### ISSUE TITLE
Consider more maintainers?

### ISSUE THREAD

**Issue by jcs090218** [ziglang/zig-mode#98]
First of all, thanks for this awesome package! 🚀 

I wonder does this package needs more maintainers? 🤔If so, I would like volunteer myself. I had this question because there were trivial issues, and PRs were left unresponsed.

I serve as the primary maintainer for [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard) and one of the maintainers for [lsp-mode](https://github.com/emacs-lsp/lsp-mode) (focus on contributing to `lsp-zig.el`). I have developed over a hundred Emacs packages. I hope I am qualified to help maintain this package.

Cheers!

**Comment by andrewrk** [comment]
Considering there are approximately 0 active maintainers I think your efforts would be well-received.

Invitation sent. Go nuts!

**Comment by jcs090218** [comment]
Thank you!

**Comment by jcs090218** [comment]
Actually, would you mind adding me to the org? I work better when I can link to the repository I am maintaining under my GitHub profile (through the organizations’ icon).

@andrewrk I've tried to ask the following question in the discord, but no one has responded. Therefore, I'm asking the question here. The question: I would like to learn more about Zig’s built-in package manager (zon) since that's the most annoying hassle for me to develop software in Zig. Are there any good resources to learn about this? I would like to know the architecture and your vision. Would it be centralized or decentralized? Etc. I hope I'm eventually able to contribute to the core. Thanks!

**Comment by andrewrk** [comment]
No, you're definitely not part of the ziglang organization, at least not yet. It takes a long time to become a core team member.

**Comment by jcs090218** [comment]
Got it. Thank you for your reply!
